/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_40;

import java.awt.Color;

/**
 *
 * @author michael
 */
public class fConsumo extends javax.swing.JFrame {

    /**
     * Creates new form fConsumo
     */
    public fConsumo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_kms = new javax.swing.JLabel();
        lbl_lts = new javax.swing.JLabel();
        txt_kms = new javax.swing.JTextField();
        txt_lts = new javax.swing.JTextField();
        btnConsumo = new javax.swing.JButton();
        lbl_consumo = new javax.swing.JLabel();
        btnApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_kms.setText("Quantos kms percorreu?");
        getContentPane().add(lbl_kms, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        lbl_lts.setText("Quantos lts gastou?");
        getContentPane().add(lbl_lts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

        txt_kms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_kms, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, -1));

        txt_lts.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_lts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        btnConsumo.setText("Calcular Consumo");
        btnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(lbl_consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 210, 50));

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoActionPerformed
        // TODO add your handling code here:        
        double lts, kms;
        String resultado = "";
        lts = Double.parseDouble(txt_lts.getText());
        kms = Double.parseDouble(txt_kms.getText());
        double consumo = (lts*100)/kms;
        
        if (consumo<=8)
            resultado = "Consumo BAIXO, CM =" + consumo;
            lbl_consumo.setForeground(Color.green);
            
        if (consumo>8 && consumo<12)
            resultado = "Consumo MÉDIO, CM =" + consumo;
            lbl_consumo.setForeground(Color.yellow);
            
        if (consumo>=12)
            resultado = "Consumo ALTO, CM =" + consumo;
            lbl_consumo.setForeground(Color.red);
        
        lbl_consumo.setText(resultado);
    }//GEN-LAST:event_btnConsumoActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        txt_kms.setText("0");
        txt_lts.setText("0");
        lbl_consumo.setText("");
    }//GEN-LAST:event_btnApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fConsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnConsumo;
    public javax.swing.JLabel lbl_consumo;
    private javax.swing.JLabel lbl_kms;
    private javax.swing.JLabel lbl_lts;
    private javax.swing.JTextField txt_kms;
    private javax.swing.JTextField txt_lts;
    // End of variables declaration//GEN-END:variables
}
