/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_49;

import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class fForca_palavra extends javax.swing.JFrame {
    public int letras;
    /**
     * Creates new form fForca_palavra
     */
    public fForca_palavra() {
        initComponents();
        //ocultar as letras
        lbl_letra1.setVisible(false);
        lbl_letra2.setVisible(false);
        lbl_letra3.setVisible(false);
        lbl_letra4.setVisible(false);
        lbl_letra5.setVisible(false);
        lbl_letra6.setVisible(false);
        lbl_letra7.setVisible(false);        
        //ocultar as imagens
        lbl_erro0.setVisible(true);
        lbl_erro1.setVisible(false);
        lbl_erro2.setVisible(false);
        lbl_erro3.setVisible(false);
        lbl_erro4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_a = new javax.swing.JButton();
        b_b = new javax.swing.JButton();
        b_c = new javax.swing.JButton();
        b_d = new javax.swing.JButton();
        b_e = new javax.swing.JButton();
        b_f = new javax.swing.JButton();
        b_g = new javax.swing.JButton();
        b_h = new javax.swing.JButton();
        b_i = new javax.swing.JButton();
        b_j = new javax.swing.JButton();
        b_k = new javax.swing.JButton();
        b_l = new javax.swing.JButton();
        b_m = new javax.swing.JButton();
        b_n = new javax.swing.JButton();
        b_o = new javax.swing.JButton();
        b_p = new javax.swing.JButton();
        b_q = new javax.swing.JButton();
        b_r = new javax.swing.JButton();
        b_s = new javax.swing.JButton();
        b_t = new javax.swing.JButton();
        b_u = new javax.swing.JButton();
        b_v = new javax.swing.JButton();
        b_w = new javax.swing.JButton();
        b_y = new javax.swing.JButton();
        b_x = new javax.swing.JButton();
        b_z = new javax.swing.JButton();
        lbl_letra1 = new javax.swing.JLabel();
        lbl_letra2 = new javax.swing.JLabel();
        lbl_letra3 = new javax.swing.JLabel();
        lbl_letra4 = new javax.swing.JLabel();
        lbl_letra5 = new javax.swing.JLabel();
        lbl_letra6 = new javax.swing.JLabel();
        lbl_letra7 = new javax.swing.JLabel();
        lbl_u1 = new javax.swing.JLabel();
        lbl_u2 = new javax.swing.JLabel();
        lbl_u3 = new javax.swing.JLabel();
        lbl_u4 = new javax.swing.JLabel();
        lbl_u5 = new javax.swing.JLabel();
        lbl_u6 = new javax.swing.JLabel();
        lbl_u7 = new javax.swing.JLabel();
        lbl_erros = new javax.swing.JLabel();
        lbl_erro0 = new javax.swing.JLabel();
        lbl_erro1 = new javax.swing.JLabel();
        lbl_erro2 = new javax.swing.JLabel();
        lbl_erro3 = new javax.swing.JLabel();
        lbl_erro4 = new javax.swing.JLabel();
        lbl_txt_erros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_a.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_a.setText("A");
        b_a.setMaximumSize(new java.awt.Dimension(50, 50));
        b_a.setMinimumSize(new java.awt.Dimension(25, 25));
        b_a.setPreferredSize(new java.awt.Dimension(50, 50));
        b_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aActionPerformed(evt);
            }
        });
        getContentPane().add(b_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        b_b.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_b.setText("B");
        b_b.setMaximumSize(new java.awt.Dimension(50, 50));
        b_b.setMinimumSize(new java.awt.Dimension(25, 25));
        b_b.setPreferredSize(new java.awt.Dimension(50, 50));
        b_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bActionPerformed(evt);
            }
        });
        getContentPane().add(b_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        b_c.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_c.setText("C");
        b_c.setMaximumSize(new java.awt.Dimension(50, 50));
        b_c.setMinimumSize(new java.awt.Dimension(25, 25));
        b_c.setPreferredSize(new java.awt.Dimension(50, 50));
        b_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cActionPerformed(evt);
            }
        });
        getContentPane().add(b_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        b_d.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_d.setText("D");
        b_d.setMaximumSize(new java.awt.Dimension(50, 50));
        b_d.setMinimumSize(new java.awt.Dimension(25, 25));
        b_d.setPreferredSize(new java.awt.Dimension(50, 50));
        b_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dActionPerformed(evt);
            }
        });
        getContentPane().add(b_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        b_e.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_e.setText("E");
        b_e.setMaximumSize(new java.awt.Dimension(50, 50));
        b_e.setMinimumSize(new java.awt.Dimension(25, 25));
        b_e.setPreferredSize(new java.awt.Dimension(50, 50));
        b_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eActionPerformed(evt);
            }
        });
        getContentPane().add(b_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        b_f.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_f.setText("F");
        b_f.setMaximumSize(new java.awt.Dimension(50, 50));
        b_f.setMinimumSize(new java.awt.Dimension(25, 25));
        b_f.setPreferredSize(new java.awt.Dimension(50, 50));
        b_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_fActionPerformed(evt);
            }
        });
        getContentPane().add(b_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        b_g.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_g.setText("G");
        b_g.setMaximumSize(new java.awt.Dimension(50, 50));
        b_g.setMinimumSize(new java.awt.Dimension(25, 25));
        b_g.setPreferredSize(new java.awt.Dimension(50, 50));
        b_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gActionPerformed(evt);
            }
        });
        getContentPane().add(b_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        b_h.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_h.setText("H");
        b_h.setMaximumSize(new java.awt.Dimension(50, 50));
        b_h.setMinimumSize(new java.awt.Dimension(25, 25));
        b_h.setPreferredSize(new java.awt.Dimension(50, 50));
        b_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hActionPerformed(evt);
            }
        });
        getContentPane().add(b_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        b_i.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_i.setText("I");
        b_i.setMaximumSize(new java.awt.Dimension(50, 50));
        b_i.setMinimumSize(new java.awt.Dimension(25, 25));
        b_i.setPreferredSize(new java.awt.Dimension(50, 50));
        b_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iActionPerformed(evt);
            }
        });
        getContentPane().add(b_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        b_j.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_j.setText("J");
        b_j.setMaximumSize(new java.awt.Dimension(50, 50));
        b_j.setMinimumSize(new java.awt.Dimension(25, 25));
        b_j.setPreferredSize(new java.awt.Dimension(50, 50));
        b_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_jActionPerformed(evt);
            }
        });
        getContentPane().add(b_j, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        b_k.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_k.setText("K");
        b_k.setMaximumSize(new java.awt.Dimension(50, 50));
        b_k.setMinimumSize(new java.awt.Dimension(25, 25));
        b_k.setPreferredSize(new java.awt.Dimension(50, 50));
        b_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kActionPerformed(evt);
            }
        });
        getContentPane().add(b_k, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        b_l.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_l.setText("L");
        b_l.setMaximumSize(new java.awt.Dimension(50, 50));
        b_l.setMinimumSize(new java.awt.Dimension(25, 25));
        b_l.setPreferredSize(new java.awt.Dimension(50, 50));
        b_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lActionPerformed(evt);
            }
        });
        getContentPane().add(b_l, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        b_m.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_m.setText("M");
        b_m.setMaximumSize(new java.awt.Dimension(50, 50));
        b_m.setMinimumSize(new java.awt.Dimension(25, 25));
        b_m.setPreferredSize(new java.awt.Dimension(50, 50));
        b_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mActionPerformed(evt);
            }
        });
        getContentPane().add(b_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        b_n.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_n.setText("N");
        b_n.setMaximumSize(new java.awt.Dimension(50, 50));
        b_n.setMinimumSize(new java.awt.Dimension(25, 25));
        b_n.setPreferredSize(new java.awt.Dimension(50, 50));
        b_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nActionPerformed(evt);
            }
        });
        getContentPane().add(b_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        b_o.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_o.setText("O");
        b_o.setMaximumSize(new java.awt.Dimension(50, 50));
        b_o.setMinimumSize(new java.awt.Dimension(25, 25));
        b_o.setPreferredSize(new java.awt.Dimension(50, 50));
        b_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_oActionPerformed(evt);
            }
        });
        getContentPane().add(b_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        b_p.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_p.setText("P");
        b_p.setMaximumSize(new java.awt.Dimension(50, 50));
        b_p.setMinimumSize(new java.awt.Dimension(25, 25));
        b_p.setPreferredSize(new java.awt.Dimension(50, 50));
        b_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pActionPerformed(evt);
            }
        });
        getContentPane().add(b_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        b_q.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_q.setText("Q");
        b_q.setMaximumSize(new java.awt.Dimension(50, 50));
        b_q.setMinimumSize(new java.awt.Dimension(25, 25));
        b_q.setPreferredSize(new java.awt.Dimension(50, 50));
        b_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_qActionPerformed(evt);
            }
        });
        getContentPane().add(b_q, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        b_r.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_r.setText("R");
        b_r.setMaximumSize(new java.awt.Dimension(50, 50));
        b_r.setMinimumSize(new java.awt.Dimension(25, 25));
        b_r.setPreferredSize(new java.awt.Dimension(50, 50));
        b_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rActionPerformed(evt);
            }
        });
        getContentPane().add(b_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        b_s.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_s.setText("S");
        b_s.setMaximumSize(new java.awt.Dimension(50, 50));
        b_s.setMinimumSize(new java.awt.Dimension(25, 25));
        b_s.setPreferredSize(new java.awt.Dimension(50, 50));
        b_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sActionPerformed(evt);
            }
        });
        getContentPane().add(b_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        b_t.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_t.setText("T");
        b_t.setMaximumSize(new java.awt.Dimension(50, 50));
        b_t.setMinimumSize(new java.awt.Dimension(25, 25));
        b_t.setPreferredSize(new java.awt.Dimension(50, 50));
        b_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tActionPerformed(evt);
            }
        });
        getContentPane().add(b_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        b_u.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_u.setText("U");
        b_u.setMaximumSize(new java.awt.Dimension(50, 50));
        b_u.setMinimumSize(new java.awt.Dimension(25, 25));
        b_u.setPreferredSize(new java.awt.Dimension(50, 50));
        b_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_uActionPerformed(evt);
            }
        });
        getContentPane().add(b_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        b_v.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_v.setText("V");
        b_v.setMaximumSize(new java.awt.Dimension(50, 50));
        b_v.setMinimumSize(new java.awt.Dimension(25, 25));
        b_v.setPreferredSize(new java.awt.Dimension(50, 50));
        b_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_vActionPerformed(evt);
            }
        });
        getContentPane().add(b_v, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        b_w.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_w.setText("W");
        b_w.setMaximumSize(new java.awt.Dimension(50, 50));
        b_w.setMinimumSize(new java.awt.Dimension(25, 25));
        b_w.setPreferredSize(new java.awt.Dimension(50, 50));
        b_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_wActionPerformed(evt);
            }
        });
        getContentPane().add(b_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        b_y.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_y.setText("Y");
        b_y.setMaximumSize(new java.awt.Dimension(50, 50));
        b_y.setMinimumSize(new java.awt.Dimension(25, 25));
        b_y.setPreferredSize(new java.awt.Dimension(50, 50));
        b_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_yActionPerformed(evt);
            }
        });
        getContentPane().add(b_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        b_x.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_x.setText("X");
        b_x.setMaximumSize(new java.awt.Dimension(50, 50));
        b_x.setMinimumSize(new java.awt.Dimension(25, 25));
        b_x.setPreferredSize(new java.awt.Dimension(50, 50));
        b_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_xActionPerformed(evt);
            }
        });
        getContentPane().add(b_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        b_z.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_z.setText("Z");
        b_z.setMaximumSize(new java.awt.Dimension(50, 50));
        b_z.setMinimumSize(new java.awt.Dimension(25, 25));
        b_z.setPreferredSize(new java.awt.Dimension(50, 50));
        b_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_zActionPerformed(evt);
            }
        });
        getContentPane().add(b_z, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        lbl_letra1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra1.setText("P");
        lbl_letra1.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lbl_letra2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra2.setText("R");
        lbl_letra2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, -1));

        lbl_letra3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra3.setText("I");
        lbl_letra3.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        lbl_letra4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra4.setText("V");
        lbl_letra4.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        lbl_letra5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra5.setText("A");
        lbl_letra5.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        lbl_letra6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra6.setText("T");
        lbl_letra6.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lbl_letra7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra7.setText("E");
        lbl_letra7.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        lbl_u1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u1.setText("_");
        getContentPane().add(lbl_u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lbl_u2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u2.setText("_");
        getContentPane().add(lbl_u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        lbl_u3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u3.setText("_");
        getContentPane().add(lbl_u3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        lbl_u4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u4.setText("_");
        getContentPane().add(lbl_u4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        lbl_u5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u5.setText("_");
        getContentPane().add(lbl_u5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        lbl_u6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u6.setText("_");
        getContentPane().add(lbl_u6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        lbl_u7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u7.setText("_");
        getContentPane().add(lbl_u7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        lbl_erros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_erros.setText("0");
        getContentPane().add(lbl_erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 30, 90));

        lbl_erro0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_49/erro_0.jpg"))); // NOI18N
        getContentPane().add(lbl_erro0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 220));

        lbl_erro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_49/erro_1.jpg"))); // NOI18N
        getContentPane().add(lbl_erro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 220));

        lbl_erro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_49/erro_2.jpg"))); // NOI18N
        getContentPane().add(lbl_erro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 220));

        lbl_erro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_49/erro_3.jpg"))); // NOI18N
        getContentPane().add(lbl_erro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 220));

        lbl_erro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_49/erro_4.jpg"))); // NOI18N
        getContentPane().add(lbl_erro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 90, 220));

        lbl_txt_erros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_txt_erros.setText("Erros:");
        getContentPane().add(lbl_txt_erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verifica_vitoria(){
        if (letras == 7){
        String msg = "<html>PARABÉNS! GANHOU!<br>Quer jogar novamente?";
        int valor = JOptionPane.showConfirmDialog(null, msg);
        /* yes -> valor = 0, no -> valor = 1, cancel -> valor = 2 */
            if (valor==0){
                inicia();
            }
            else
                this.dispose();
        }
    }
    public void inicia(){
        letras = 0;
        //ocultar todas as imagens
        lbl_erro0.setVisible(true);
        lbl_erro1.setVisible(false);        
        lbl_erro2.setVisible(false);
        lbl_erro3.setVisible(false);
        lbl_erro4.setVisible(false);
        //ocultar as letras
        lbl_letra1.setVisible(false);
        lbl_letra2.setVisible(false);
        lbl_letra3.setVisible(false);
        lbl_letra4.setVisible(false);
        lbl_letra5.setVisible(false);
        lbl_letra6.setVisible(false);
        lbl_letra7.setVisible(false);
        //reiniciar os erros a zero
        lbl_erros.setText("0");
        //colocar os botões das letras ativos
        b_a.setEnabled(true);
        b_b.setEnabled(true);
        b_c.setEnabled(true);
        b_d.setEnabled(true);
        b_e.setEnabled(true);
        b_f.setEnabled(true);
        b_g.setEnabled(true);
        b_h.setEnabled(true);
        b_i.setEnabled(true);
        b_j.setEnabled(true);
        b_k.setEnabled(true);
        b_l.setEnabled(true);
        b_m.setEnabled(true);
        b_n.setEnabled(true);
        b_o.setEnabled(true);
        b_p.setEnabled(true);
        b_q.setEnabled(true);
        b_r.setEnabled(true);
        b_s.setEnabled(true);
        b_t.setEnabled(true);
        b_u.setEnabled(true);
        b_v.setEnabled(true);
        b_w.setEnabled(true);
        b_x.setEnabled(true);
        b_y.setEnabled(true);
        b_z.setEnabled(true);
    }
    public void perdeu(){
        String msg = "<html>PERDEU!<br>Quer jogar novamente?";
        int valor = JOptionPane.showConfirmDialog(null, msg);
        /* yes -> valor = 0, no -> valor = 1, cancel -> valor = 2 */
        if (valor==0){
            inicia();
        }
        else
            this.dispose();
    }
    public void troca_imagem(){
        int erros = Integer.parseInt(lbl_erros.getText());
        erros ++;
        lbl_erros.setText(erros + "");
        if (erros==1){
            lbl_erro0.setVisible(false);
            lbl_erro1.setVisible(true);
        }
        else if (erros==2){
            lbl_erro1.setVisible(false);
            lbl_erro2.setVisible(true);
        }
        else if (erros==3){
            lbl_erro2.setVisible(false);
            lbl_erro3.setVisible(true);
        }
        else{
            lbl_erro3.setVisible(false);
            lbl_erro4.setVisible(true);
        }
    }
    private void b_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bActionPerformed
        // TODO add your handling code here:
        this.b_b.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_bActionPerformed

    private void b_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra5.setVisible(true);
        this.b_a.setEnabled(false);
        verifica_vitoria();     
    }//GEN-LAST:event_b_aActionPerformed

    private void b_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dActionPerformed
        // TODO add your handling code here:
        this.b_d.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_dActionPerformed

    private void b_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cActionPerformed
        // TODO add your handling code here:
        this.b_c.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_cActionPerformed

    private void b_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_fActionPerformed
        // TODO add your handling code here:
        this.b_f.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_fActionPerformed

    private void b_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra7.setVisible(true);
        this.b_e.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_eActionPerformed

    private void b_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_zActionPerformed
        // TODO add your handling code here:
        this.b_z.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_zActionPerformed

    private void b_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gActionPerformed
        // TODO add your handling code here:
        this.b_g.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_gActionPerformed

    private void b_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra3.setVisible(true);
        this.b_i.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_iActionPerformed

    private void b_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hActionPerformed
        // TODO add your handling code here:
        this.b_h.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_hActionPerformed

    private void b_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kActionPerformed
        // TODO add your handling code here:
        this.b_k.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_kActionPerformed

    private void b_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_jActionPerformed
        // TODO add your handling code here:
        this.b_j.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_jActionPerformed

    private void b_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mActionPerformed
        // TODO add your handling code here:
        this.b_m.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_mActionPerformed

    private void b_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lActionPerformed
        // TODO add your handling code here:
        this.b_l.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_lActionPerformed

    private void b_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nActionPerformed
        // TODO add your handling code here:
        this.b_n.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_nActionPerformed

    private void b_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra1.setVisible(true);
        this.b_p.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_pActionPerformed

    private void b_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_oActionPerformed
        // TODO add your handling code here:
        this.b_o.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_oActionPerformed

    private void b_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra2.setVisible(true);
        this.b_r.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_rActionPerformed

    private void b_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_qActionPerformed
        // TODO add your handling code here:
        this.b_q.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_qActionPerformed

    private void b_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra6.setVisible(true);
        this.b_t.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_tActionPerformed

    private void b_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sActionPerformed
        // TODO add your handling code here:
        this.b_s.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_sActionPerformed

    private void b_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_uActionPerformed
        // TODO add your handling code here:
        this.b_u.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_uActionPerformed

    private void b_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_vActionPerformed
        // TODO add your handling code here:
        //Quando clico V
        letras++;
        lbl_letra4.setVisible(true);
        this.b_v.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_b_vActionPerformed

    private void b_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_wActionPerformed
        // TODO add your handling code here:
        this.b_w.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_wActionPerformed

    private void b_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_yActionPerformed
        // TODO add your handling code here:
        this.b_y.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_yActionPerformed

    private void b_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_xActionPerformed
        // TODO add your handling code here:
        this.b_x.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
        perdeu();
        else
        troca_imagem();
    }//GEN-LAST:event_b_xActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fForca_palavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fForca_palavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fForca_palavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fForca_palavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fForca_palavra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b_a;
    public javax.swing.JButton b_b;
    public javax.swing.JButton b_c;
    public javax.swing.JButton b_d;
    public javax.swing.JButton b_e;
    public javax.swing.JButton b_f;
    public javax.swing.JButton b_g;
    public javax.swing.JButton b_h;
    public javax.swing.JButton b_i;
    public javax.swing.JButton b_j;
    public javax.swing.JButton b_k;
    public javax.swing.JButton b_l;
    public javax.swing.JButton b_m;
    public javax.swing.JButton b_n;
    public javax.swing.JButton b_o;
    public javax.swing.JButton b_p;
    public javax.swing.JButton b_q;
    public javax.swing.JButton b_r;
    public javax.swing.JButton b_s;
    public javax.swing.JButton b_t;
    public javax.swing.JButton b_u;
    public javax.swing.JButton b_v;
    public javax.swing.JButton b_w;
    public javax.swing.JButton b_x;
    public javax.swing.JButton b_y;
    public javax.swing.JButton b_z;
    public javax.swing.JLabel lbl_erro0;
    public javax.swing.JLabel lbl_erro1;
    public javax.swing.JLabel lbl_erro2;
    public javax.swing.JLabel lbl_erro3;
    public javax.swing.JLabel lbl_erro4;
    public javax.swing.JLabel lbl_erros;
    public javax.swing.JLabel lbl_letra1;
    public javax.swing.JLabel lbl_letra2;
    public javax.swing.JLabel lbl_letra3;
    public javax.swing.JLabel lbl_letra4;
    public javax.swing.JLabel lbl_letra5;
    public javax.swing.JLabel lbl_letra6;
    public javax.swing.JLabel lbl_letra7;
    private javax.swing.JLabel lbl_txt_erros;
    private javax.swing.JLabel lbl_u1;
    private javax.swing.JLabel lbl_u2;
    private javax.swing.JLabel lbl_u3;
    private javax.swing.JLabel lbl_u4;
    private javax.swing.JLabel lbl_u5;
    private javax.swing.JLabel lbl_u6;
    private javax.swing.JLabel lbl_u7;
    // End of variables declaration//GEN-END:variables
}
