/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import javax.swing.JOptionPane;

/**
 * Data: 24/11/2025
 * @author michael
 */
public class jCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form jCalculadora
     */
    public jCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnDividir1 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnSomar1 = new javax.swing.JButton();
        btnSubtrair1 = new javax.swing.JButton();
        btnMultiplicar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Número 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("lblNum2");

        jLabel2.setText("Número 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("lblNum2");

        getContentPane().add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 20));
        txtNum1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 200, 20));
        txtNum2.getAccessibleContext().setAccessibleName("");

        btnReset.setText("RESET");
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        btnReset.getAccessibleContext().setAccessibleName("");

        btnDividir1.setText("DIVIDIR");
        btnDividir1.setToolTipText("");
        btnDividir1.setActionCommand("DIVIDIR");
        btnDividir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        btnDividir1.getAccessibleContext().setAccessibleName("");

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResultado.setText("RESULTADO:");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));
        lblResultado.getAccessibleContext().setAccessibleName("");

        btnSomar1.setText("SOMAR");
        btnSomar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btnSubtrair1.setText("SUBTRAIR");
        btnSubtrair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrair1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtrair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btnMultiplicar1.setText("MULTIPLICAR");
        btnMultiplicar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDividir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividir1ActionPerformed
        // TODO add your handling code here:
        float n1, n2, div;
        
        n1 = Float.parseFloat(txtNum1.getText());
        n2 = Float.parseFloat(txtNum2.getText());
        
        if (n2==0){
            lblResultado.setText("Não é possivel dividir por zero");
        }
        else{
            div = n1 / n2;
            lblResultado.setText(String.valueOf("Resultado: " + div));
            txtNum1.setText("");
            txtNum2.setText("");
            txtNum1.requestFocus();
        }        
    }//GEN-LAST:event_btnDividir1ActionPerformed

    private void btnSomar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomar1ActionPerformed
        // TODO add your handling code here:
        float n1, n2, soma;
        
        n1 = Float.parseFloat(txtNum1.getText());
        n2 = Float.parseFloat(txtNum2.getText());
        soma = n1 + n2;
        lblResultado.setText(String.valueOf("Resultado: " + soma));
        txtNum1.setText("");
        txtNum2.setText("");
        txtNum1.requestFocus();
    }//GEN-LAST:event_btnSomar1ActionPerformed

    private void btnSubtrair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrair1ActionPerformed
        // TODO add your handling code here:
        float n1, n2, sub;
        
        n1 = Float.parseFloat(txtNum1.getText());
        n2 = Float.parseFloat(txtNum2.getText());
        sub = n1 - n2;
        lblResultado.setText(String.valueOf("Resultado: " + sub));
        txtNum1.setText("");
        txtNum2.setText("");
        txtNum1.requestFocus();
    }//GEN-LAST:event_btnSubtrair1ActionPerformed

    private void btnMultiplicar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicar1ActionPerformed
        // TODO add your handling code here:
        float n1, n2, mult;
        
        n1 = Float.parseFloat(txtNum1.getText());
        n2 = Float.parseFloat(txtNum2.getText());
        mult = n1 * n2;
        lblResultado.setText(String.valueOf("Resultado: " + mult));
        txtNum1.setText("");
        txtNum2.setText("");
        txtNum1.requestFocus();
    }//GEN-LAST:event_btnMultiplicar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir1;
    private javax.swing.JButton btnMultiplicar1;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSomar1;
    private javax.swing.JButton btnSubtrair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lblResultado;
    public javax.swing.JTextField txtNum1;
    public javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
