/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_46;

/**
 *
 * @author michael
 * Função: calcular salário
 */
public class fSalario extends javax.swing.JFrame {

    /**
     * Creates new form fSalario
     */
    public fSalario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_horas = new javax.swing.JLabel();
        txt_horas = new javax.swing.JTextField();
        lbl_resultado = new javax.swing.JLabel();
        btn_calc = new javax.swing.JButton();
        btn_Apagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_horas.setText("Insira as horas de laboração:");
        getContentPane().add(lbl_horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, -1));

        txt_horas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, -1));

        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 110));

        btn_calc.setText("Calcular");
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btn_Apagar.setText("Apagar");
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed
        // TODO add your handling code here:
        int h = Integer.parseInt(txt_horas.getText());       
        int bruto = h * 10;
        double desconto = bruto *0.25;
        double liq = bruto - desconto;
        String resultado;
        
        if (liq<400){
            resultado = "ABAIXO DO SALÁRIO MÉDIO";
        }
        else if (liq>=400 && liq<600){
            resultado = "SALÁRIO MÉDIO";
        }
        else{
            resultado = "ACIMA DO SALÁRIO MÉDIO";
        }        
        lbl_resultado.setText("<html>Salário bruto: " + bruto 
                + "<br>Descontos: " + desconto 
                + "<br>Salário líquido: " + liq + "<br>" + resultado); 
    }//GEN-LAST:event_btn_calcActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        txt_horas.setText("");
        lbl_resultado.setText("");
    }//GEN-LAST:event_btn_ApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fSalario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fSalario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Apagar;
    private javax.swing.JButton btn_calc;
    private javax.swing.JLabel lbl_horas;
    public javax.swing.JLabel lbl_resultado;
    public javax.swing.JTextField txt_horas;
    // End of variables declaration//GEN-END:variables
}
