/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_44;

/**
 *
 * @author michael
 */
public class fClassTri extends javax.swing.JFrame {

    /**
     * Creates new form fClassTri
     */
    public fClassTri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_triangulo = new javax.swing.JLabel();
        lbl_lado1 = new javax.swing.JLabel();
        lbl_lado2 = new javax.swing.JLabel();
        lbl_lado3 = new javax.swing.JLabel();
        txt_lado1 = new javax.swing.JTextField();
        txt_lado2 = new javax.swing.JTextField();
        txt_lado3 = new javax.swing.JTextField();
        lbl_resultado = new javax.swing.JLabel();
        btn_submeter = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_triangulo.setText("Insira os lados do triángulo:");
        getContentPane().add(lbl_triangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, 20));

        lbl_lado1.setText("Lado 1:");
        getContentPane().add(lbl_lado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 150, -1));

        lbl_lado2.setText("Lado 2:");
        getContentPane().add(lbl_lado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 150, -1));

        lbl_lado3.setText("Lado 3:");
        getContentPane().add(lbl_lado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, -1));
        getContentPane().add(txt_lado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, -1));
        getContentPane().add(txt_lado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 160, -1));
        getContentPane().add(txt_lado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        lbl_resultado.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 290, 90));

        btn_submeter.setText("Submeter");
        btn_submeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submeterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        btn_apagar.setText("Apagar");
        btn_apagar.setMaximumSize(new java.awt.Dimension(85, 23));
        btn_apagar.setPreferredSize(new java.awt.Dimension(81, 23));
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submeterActionPerformed
        // TODO add your handling code here:
        double lado1 = Double.parseDouble(txt_lado1.getText());
        double lado2 = Double.parseDouble(txt_lado2.getText());
        double lado3 = Double.parseDouble(txt_lado3.getText());
        
        if (lado1 == lado2 && lado2 == lado3){            
            lbl_resultado.setText("Os lados inseridos formam um triángulo "
                    + "equilátero ");
        }
        else if (lado1 != lado2 && lado2 != lado3 && lado3 != lado1){            
            lbl_resultado.setText("Os lados inseridos formam um triángulo "
                    + "escaleno ");
        }
        else{            
            lbl_resultado.setText("Os lados inseridos formam um triángulo "
                    + "isósceles ");
        }
    }//GEN-LAST:event_btn_submeterActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        // TODO add your handling code here:
        txt_lado1.setText("");
        txt_lado2.setText("");
        txt_lado3.setText("");
        lbl_resultado.setText("");
    }//GEN-LAST:event_btn_apagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fClassTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fClassTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fClassTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fClassTri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fClassTri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_submeter;
    private javax.swing.JLabel lbl_lado1;
    private javax.swing.JLabel lbl_lado2;
    private javax.swing.JLabel lbl_lado3;
    public javax.swing.JLabel lbl_resultado;
    private javax.swing.JLabel lbl_triangulo;
    public javax.swing.JTextField txt_lado1;
    public javax.swing.JTextField txt_lado2;
    public javax.swing.JTextField txt_lado3;
    // End of variables declaration//GEN-END:variables
}
