/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_45;

/**
 *
 * @author michael
 */
public class fEstacionamento extends javax.swing.JFrame {

    /**
     * Creates new form fEstacionamento
     */
    public fEstacionamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tempo = new javax.swing.JLabel();
        txt_h = new javax.swing.JTextField();
        lbl_resultado = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        btn_Apagar = new javax.swing.JButton();
        lbl_h = new javax.swing.JLabel();
        lbl_min = new javax.swing.JLabel();
        txt_min = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tempo.setText("Insira o tempo do estacionamento:");
        getContentPane().add(lbl_tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 300, -1));

        txt_h.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 80, -1));
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, 80));

        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        btn_Apagar.setText("Apagar");
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lbl_h.setText("Horas:");
        getContentPane().add(lbl_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, -1));

        lbl_min.setText("Minutos:");
        getContentPane().add(lbl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txt_min.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txt_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        int h = Integer.parseInt(txt_h.getText());
        int min = Integer.parseInt(txt_min.getText());
        double tempo = (h + (min/60.0));
        double valor = 0.0;        
        
        if (tempo<=0){            
            lbl_resultado.setText("Valor a pagar: " + valor + "€");
            return;
        }
        else if (tempo<=1){
            valor = 1.0;            
        }
        else if (tempo<=2){
            valor = 1.0 + 0.8;            
        }
        else {
            double extra = tempo - 2;
            double blocos = Math.ceil(extra);
            valor = 1.0 + 0.8 + (blocos*0.4);
        }
        String resultado = "O valor a pagar é " + valor + "€";
        lbl_resultado.setText(resultado);
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // TODO add your handling code here:
        txt_h.setText("");
        txt_min.setText("");
        lbl_resultado.setText("");
    }//GEN-LAST:event_btn_ApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fEstacionamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Apagar;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel lbl_h;
    private javax.swing.JLabel lbl_min;
    public javax.swing.JLabel lbl_resultado;
    private javax.swing.JLabel lbl_tempo;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_min;
    // End of variables declaration//GEN-END:variables
}
