/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_51;

import javax.swing.JOptionPane;
// biblioteca a usar para o audio
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author michael
 */
public class fPokemon extends javax.swing.JFrame {

    /**
     * Creates new form fPokemon
     */
    public fPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pokemon = new javax.swing.JLabel();
        lbl_texto = new javax.swing.JLabel();
        lbl_pontos = new javax.swing.JLabel();
        lbl_pic1 = new javax.swing.JLabel();
        lbl_pic2 = new javax.swing.JLabel();
        lbl_pic3 = new javax.swing.JLabel();
        lbl_pic4 = new javax.swing.JLabel();
        lbl_pic5 = new javax.swing.JLabel();
        lbl_pic6 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_pokemon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_pokemon.setText("Venusaur");
        getContentPane().add(lbl_pokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 40));

        lbl_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_texto.setText("Pontos:");
        getContentPane().add(lbl_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        lbl_pontos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_pontos.setText("0");
        getContentPane().add(lbl_pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 50, 20));

        lbl_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic1.jpg"))); // NOI18N
        getContentPane().add(lbl_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 170));

        lbl_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic2.jpg"))); // NOI18N
        getContentPane().add(lbl_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 170));

        lbl_pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic3.jpg"))); // NOI18N
        getContentPane().add(lbl_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 170, 170));

        lbl_pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic4.jpg"))); // NOI18N
        getContentPane().add(lbl_pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 170, 170));

        lbl_pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic5.jpg"))); // NOI18N
        getContentPane().add(lbl_pic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 170, 170));

        lbl_pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_51/pic6.jpg"))); // NOI18N
        getContentPane().add(lbl_pic6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 170, 170));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn1.setText("?");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn2.setText("?");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 170, -1));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn3.setText("?");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 170, -1));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn4.setText("?");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 170, -1));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn5.setText("?");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 170, -1));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn6.setText("?");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void acertou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\ex_51\\src\\ex_51\\Audio\\sucesso.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void ganhou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\ex_51\\src\\ex_51\\Audio\\ganhou.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void errou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\ex_51\\src\\ex_51\\Audio\\erro.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText()=="?"){
            if (lbl_pokemon.getText()=="Venusaur"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Já apanhou mais um!");
                lbl_pokemon.setText("Bulbasaur");
                btn3.setText("Venusaur");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText()=="?"){
            if (lbl_pokemon.getText()=="Bulbasaur"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Já apanhou mais um!");
                lbl_pokemon.setText("Poliwag");
                btn1.setText("Bulbasaur");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn5.getText()=="?"){
            if (lbl_pokemon.getText()=="Poliwag"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Já apanhou mais um!");
                lbl_pokemon.setText("Victreebel");
                btn5.setText("Poliwag");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText()=="?"){
            if (lbl_pokemon.getText()=="Victreebel"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;                
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Já apanhou mais um!");
                lbl_pokemon.setText("Psyduck");
                btn2.setText("Victreebel");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn6.getText()=="?"){
            if (lbl_pokemon.getText()=="Psyduck"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;                
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Já apanhou mais um!");
                lbl_pokemon.setText("Wartotle");
                btn6.setText("Psyduck");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn4.getText()=="?"){
            if (lbl_pokemon.getText()=="Wartotle"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;                
                lbl_pontos.setText(pts+"");
                ganhou();
                JOptionPane.showMessageDialog(null, "Apanhou todos!");
                lbl_pokemon.setText("Parabéns!");
                btn4.setText("Wartotle");            
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Volte a tentar!");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Já apanhou esse!");
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    private javax.swing.JLabel lbl_pic1;
    private javax.swing.JLabel lbl_pic2;
    private javax.swing.JLabel lbl_pic3;
    private javax.swing.JLabel lbl_pic4;
    private javax.swing.JLabel lbl_pic5;
    private javax.swing.JLabel lbl_pic6;
    public javax.swing.JLabel lbl_pokemon;
    public javax.swing.JLabel lbl_pontos;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables
}
