/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_50;

import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class fGalo extends javax.swing.JFrame {

    /**
     * Creates new form fGalo
     */
    public fGalo() {
        initComponents();
        limpa();
        carrega_jogadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_j1 = new javax.swing.JLabel();
        lbl_j2 = new javax.swing.JLabel();
        lbl_pt1 = new javax.swing.JLabel();
        lbl_pt2 = new javax.swing.JLabel();
        lbl_jogada = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn_novojogo = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_j1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_j1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_j1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_j1.setMaximumSize(new java.awt.Dimension(200, 100));
        lbl_j1.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 70, 30));

        lbl_j2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_j2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_j2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_j2.setMaximumSize(new java.awt.Dimension(200, 100));
        lbl_j2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 70, 30));

        lbl_pt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_pt1.setText("0");
        lbl_pt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_pt1.setMaximumSize(new java.awt.Dimension(10, 20));
        lbl_pt1.setMinimumSize(new java.awt.Dimension(10, 20));
        lbl_pt1.setPreferredSize(new java.awt.Dimension(10, 20));
        getContentPane().add(lbl_pt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 20, -1));

        lbl_pt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_pt2.setText("0");
        lbl_pt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_pt2.setMaximumSize(new java.awt.Dimension(10, 20));
        lbl_pt2.setMinimumSize(new java.awt.Dimension(10, 20));
        lbl_pt2.setPreferredSize(new java.awt.Dimension(10, 20));
        getContentPane().add(lbl_pt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 20, -1));

        lbl_jogada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_jogada.setForeground(new java.awt.Color(255, 0, 51));
        lbl_jogada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jogada.setText("X");
        getContentPane().add(lbl_jogada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 30, 30));

        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, 70));

        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 70));

        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 70, 70));

        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, 70));

        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 70, 70));

        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 70, 70));

        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 70, 70));

        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 70, 70));

        btn_novojogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_novojogo.setText("Novo Jogo");
        btn_novojogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_novojogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novojogoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_novojogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reset.setMaximumSize(new java.awt.Dimension(150, 27));
        btn_reset.setMinimumSize(new java.awt.Dimension(50, 27));
        btn_reset.setPreferredSize(new java.awt.Dimension(104, 27));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpa(){
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
    }    
    private void btn_novojogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novojogoActionPerformed
        // TODO add your handling code here:
        // quando clico em novo jogo
        limpa();
    }//GEN-LAST:event_btn_novojogoActionPerformed
    public void carrega_jogadores(){
        lbl_pt1.setText("0");
        lbl_pt2.setText("0");
        lbl_jogada.setText("X");
        String j1, j2;
        j1 = JOptionPane.showInputDialog(null, "Qual o nome do jogador 1?");
        lbl_j1.setText(j1);
        j2 = JOptionPane.showInputDialog(null, "Qual o nome do jogador 2?");
        lbl_j2.setText(j2);       
    }
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        // quando clico em reset
        limpa();
        carrega_jogadores();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText()==""){
            btn1.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn1.getText()==btn2.getText() && btn2.getText()==btn3.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn1.getText()==btn4.getText() && btn4.getText()==btn7.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na diagonal
            if (btn1.getText()==btn5.getText() && btn5.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText()==""){
            btn2.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn1.getText()==btn2.getText() && btn2.getText()==btn3.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn2.getText()==btn5.getText() && btn5.getText()==btn8.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText()==""){
            btn3.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn1.getText()==btn2.getText() && btn2.getText()==btn3.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn3.getText()==btn6.getText() && btn6.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na diagonal
            if (btn3.getText()==btn5.getText() && btn5.getText()==btn7.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn4.getText()==""){
            btn4.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn4.getText()==btn5.getText() && btn5.getText()==btn6.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn1.getText()==btn4.getText() && btn4.getText()==btn7.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn5.getText()==""){
            btn5.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn4.getText()==btn5.getText() && btn5.getText()==btn6.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn2.getText()==btn5.getText() && btn5.getText()==btn8.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na diagonal
            if ((btn1.getText()==btn5.getText() && 
                    btn5.getText()==btn9.getText()) || 
                   (btn3.getText()==btn5.getText() && 
                    btn5.getText()==btn7.getText())){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn6.getText()==""){
            btn6.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn4.getText()==btn5.getText() && btn5.getText()==btn6.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn3.getText()==btn6.getText() && btn6.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (btn7.getText()==""){
            btn7.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn7.getText()==btn8.getText() && btn8.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn1.getText()==btn4.getText() && btn4.getText()==btn7.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na diagonal
            if (btn3.getText()==btn5.getText() && btn5.getText()==btn7.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (btn8.getText()==""){
            btn8.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn7.getText()==btn8.getText() && btn8.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn2.getText()==btn5.getText() && btn5.getText()==btn8.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (btn9.getText()==""){
            btn9.setText(lbl_jogada.getText());
            //verificar vitória na horizontal
            if (btn7.getText()==btn8.getText() && btn8.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na vertical
            if (btn3.getText()==btn6.getText() && btn6.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // verificar vitória na diagonal
            if (btn1.getText()==btn5.getText() && btn5.getText()==btn9.getText()){
                if (lbl_jogada.getText()=="X")
                    lbl_pt1.setText(Integer.parseInt(lbl_pt1.getText())+1+"");
                else
                    lbl_pt2.setText(Integer.parseInt(lbl_pt2.getText())+1+"");
                JOptionPane.showMessageDialog(null, "Parabéns Ganhou!");
                limpa();
            }
            // trocar o jogador
            if (lbl_jogada.getText()=="X")
                lbl_jogada.setText("0");
            else
                lbl_jogada.setText("X");
        } // termina a verificação se o botão estava vazio
    }//GEN-LAST:event_btn9ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fGalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fGalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fGalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fGalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fGalo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    private javax.swing.JButton btn_novojogo;
    private javax.swing.JButton btn_reset;
    public javax.swing.JLabel lbl_j1;
    public javax.swing.JLabel lbl_j2;
    public javax.swing.JLabel lbl_jogada;
    public javax.swing.JLabel lbl_pt1;
    public javax.swing.JLabel lbl_pt2;
    // End of variables declaration//GEN-END:variables
}
