/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fv_extra;

/**
 *
 * @author michael
 */
public class fExtra extends javax.swing.JFrame {

    /**
     * Creates new form fExtra
     */
    public fExtra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_form = new javax.swing.JLabel();
        lbl_faltas = new javax.swing.JLabel();
        cb_dias = new javax.swing.JComboBox<>();
        cb_faltas = new javax.swing.JComboBox<>();
        lbl_b = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_transp = new javax.swing.JLabel();
        txt_transp = new javax.swing.JTextField();
        lbl_bolsa = new javax.swing.JLabel();
        lbl_aliment = new javax.swing.JLabel();
        lbl_t = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        chb_bolsa = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_form.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_form.setText("Nº de dias de formação:");
        lbl_form.setToolTipText("");
        lbl_form.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lbl_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lbl_faltas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_faltas.setText("Nº de dias de faltas:");
        lbl_faltas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lbl_faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));

        getContentPane().add(cb_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        getContentPane().add(cb_faltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        lbl_b.setText("O total a receber de bolsa é:");
        getContentPane().add(lbl_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lbl_a.setText("O total a receber de alimentação é:");
        getContentPane().add(lbl_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbl_transp.setText("Valores gastos Transporte:");
        getContentPane().add(lbl_transp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        getContentPane().add(txt_transp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

        lbl_bolsa.setMaximumSize(new java.awt.Dimension(40, 50));
        getContentPane().add(lbl_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 60, 20));
        getContentPane().add(lbl_aliment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 70, 20));

        lbl_t.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_t.setText("O valor total a receber é:");
        getContentPane().add(lbl_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        getContentPane().add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, 20));

        btn_calcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        btn_limpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        chb_bolsa.setText("Bolsa de formação");
        getContentPane().add(chb_bolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        int dias = Integer.parseInt(cb_dias.getSelectedItem().toString());
        int faltas = Integer.parseInt(cb_faltas.getSelectedItem().toString());
        double bolsa = (dias - faltas)*6*2.01;
        //if (chb_bolsa==true)
        double aliment = (dias - faltas)*6.00;
        double transp = Double.parseDouble(txt_transp.getText());
        double total = (bolsa + aliment + transp);
        
        lbl_bolsa.setText(bolsa+"");
        lbl_aliment.setText(aliment+"");
        lbl_total.setText(total+"");
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        cb_dias.setSelectedIndex(0);
        cb_faltas.setSelectedIndex(0);
        lbl_bolsa.setText("");
        lbl_aliment.setText("");
        txt_transp.setText("");
        lbl_total.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_calcular;
    public javax.swing.JButton btn_limpar;
    public javax.swing.JComboBox<String> cb_dias;
    public javax.swing.JComboBox<String> cb_faltas;
    public javax.swing.JCheckBox chb_bolsa;
    private javax.swing.JLabel lbl_a;
    public javax.swing.JLabel lbl_aliment;
    private javax.swing.JLabel lbl_b;
    public javax.swing.JLabel lbl_bolsa;
    private javax.swing.JLabel lbl_faltas;
    private javax.swing.JLabel lbl_form;
    private javax.swing.JLabel lbl_t;
    public javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_transp;
    public javax.swing.JTextField txt_transp;
    // End of variables declaration//GEN-END:variables
}
