/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_48;

import javax.swing.JOptionPane;

/**
 * Data: 05/12/2025
 * @author michael
 * Função: Enforcado
 */
public class fEnforcado extends javax.swing.JFrame {
    public int letras;

    /**
     * Creates new form fEnforcado
     */
    public fEnforcado() {
        initComponents();
        //ocultar as letras
        lbl_letra1.hide();
        lbl_letra2.hide();
        lbl_letra3.hide();
        lbl_letra4.hide();
        //ocultar as imagens
        lbl_erro0.setVisible(true);
        lbl_erro1.setVisible(false);
        lbl_erro2.setVisible(false);
        lbl_erro3.setVisible(false);
        lbl_erro4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_A = new javax.swing.JButton();
        B_B = new javax.swing.JButton();
        B_C = new javax.swing.JButton();
        B_D = new javax.swing.JButton();
        B_E = new javax.swing.JButton();
        B_F = new javax.swing.JButton();
        B_G = new javax.swing.JButton();
        B_H = new javax.swing.JButton();
        B_I = new javax.swing.JButton();
        B_J = new javax.swing.JButton();
        B_K = new javax.swing.JButton();
        B_L = new javax.swing.JButton();
        B_M = new javax.swing.JButton();
        B_N = new javax.swing.JButton();
        B_O = new javax.swing.JButton();
        B_P = new javax.swing.JButton();
        B_Q = new javax.swing.JButton();
        B_R = new javax.swing.JButton();
        B_S = new javax.swing.JButton();
        B_T = new javax.swing.JButton();
        B_U = new javax.swing.JButton();
        B_V = new javax.swing.JButton();
        B_W = new javax.swing.JButton();
        B_X = new javax.swing.JButton();
        B_Y = new javax.swing.JButton();
        B_Z = new javax.swing.JButton();
        lbl_letra1 = new javax.swing.JLabel();
        lbl_letra2 = new javax.swing.JLabel();
        lbl_letra3 = new javax.swing.JLabel();
        lbl_letra4 = new javax.swing.JLabel();
        lbl_u1 = new javax.swing.JLabel();
        lbl_u2 = new javax.swing.JLabel();
        lbl_u3 = new javax.swing.JLabel();
        lbl_u4 = new javax.swing.JLabel();
        lbl_erros = new javax.swing.JLabel();
        lbl_txt_erros = new javax.swing.JLabel();
        lbl_erro0 = new javax.swing.JLabel();
        lbl_erro1 = new javax.swing.JLabel();
        lbl_erro2 = new javax.swing.JLabel();
        lbl_erro3 = new javax.swing.JLabel();
        lbl_erro4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_A.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_A.setText("A");
        B_A.setMaximumSize(new java.awt.Dimension(50, 50));
        B_A.setMinimumSize(new java.awt.Dimension(25, 25));
        B_A.setPreferredSize(new java.awt.Dimension(50, 50));
        B_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AActionPerformed(evt);
            }
        });
        getContentPane().add(B_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        B_B.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_B.setText("B");
        B_B.setMaximumSize(new java.awt.Dimension(50, 50));
        B_B.setMinimumSize(new java.awt.Dimension(25, 25));
        B_B.setPreferredSize(new java.awt.Dimension(50, 50));
        B_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BActionPerformed(evt);
            }
        });
        getContentPane().add(B_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        B_C.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_C.setText("C");
        B_C.setMaximumSize(new java.awt.Dimension(50, 50));
        B_C.setMinimumSize(new java.awt.Dimension(25, 25));
        B_C.setPreferredSize(new java.awt.Dimension(50, 50));
        B_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CActionPerformed(evt);
            }
        });
        getContentPane().add(B_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        B_D.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_D.setText("D");
        B_D.setMaximumSize(new java.awt.Dimension(50, 50));
        B_D.setMinimumSize(new java.awt.Dimension(25, 25));
        B_D.setPreferredSize(new java.awt.Dimension(50, 50));
        B_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_DActionPerformed(evt);
            }
        });
        getContentPane().add(B_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        B_E.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_E.setText("E");
        B_E.setMaximumSize(new java.awt.Dimension(50, 50));
        B_E.setMinimumSize(new java.awt.Dimension(25, 25));
        B_E.setPreferredSize(new java.awt.Dimension(50, 50));
        B_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EActionPerformed(evt);
            }
        });
        getContentPane().add(B_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        B_F.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_F.setText("F");
        B_F.setMaximumSize(new java.awt.Dimension(50, 50));
        B_F.setMinimumSize(new java.awt.Dimension(25, 25));
        B_F.setPreferredSize(new java.awt.Dimension(50, 50));
        B_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FActionPerformed(evt);
            }
        });
        getContentPane().add(B_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        B_G.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_G.setText("G");
        B_G.setMaximumSize(new java.awt.Dimension(50, 50));
        B_G.setMinimumSize(new java.awt.Dimension(25, 25));
        B_G.setPreferredSize(new java.awt.Dimension(50, 50));
        B_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GActionPerformed(evt);
            }
        });
        getContentPane().add(B_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        B_H.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_H.setText("H");
        B_H.setMaximumSize(new java.awt.Dimension(50, 50));
        B_H.setMinimumSize(new java.awt.Dimension(25, 25));
        B_H.setPreferredSize(new java.awt.Dimension(50, 50));
        B_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HActionPerformed(evt);
            }
        });
        getContentPane().add(B_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        B_I.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_I.setText("I");
        B_I.setMaximumSize(new java.awt.Dimension(50, 50));
        B_I.setMinimumSize(new java.awt.Dimension(25, 25));
        B_I.setPreferredSize(new java.awt.Dimension(50, 50));
        B_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IActionPerformed(evt);
            }
        });
        getContentPane().add(B_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        B_J.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_J.setText("J");
        B_J.setMaximumSize(new java.awt.Dimension(50, 50));
        B_J.setMinimumSize(new java.awt.Dimension(25, 25));
        B_J.setPreferredSize(new java.awt.Dimension(50, 50));
        B_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_JActionPerformed(evt);
            }
        });
        getContentPane().add(B_J, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        B_K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_K.setText("K");
        B_K.setMaximumSize(new java.awt.Dimension(50, 50));
        B_K.setMinimumSize(new java.awt.Dimension(25, 25));
        B_K.setPreferredSize(new java.awt.Dimension(50, 50));
        B_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_KActionPerformed(evt);
            }
        });
        getContentPane().add(B_K, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        B_L.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_L.setText("L");
        B_L.setMaximumSize(new java.awt.Dimension(50, 50));
        B_L.setMinimumSize(new java.awt.Dimension(25, 25));
        B_L.setPreferredSize(new java.awt.Dimension(50, 50));
        B_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LActionPerformed(evt);
            }
        });
        getContentPane().add(B_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        B_M.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_M.setText("M");
        B_M.setMaximumSize(new java.awt.Dimension(50, 50));
        B_M.setMinimumSize(new java.awt.Dimension(25, 25));
        B_M.setPreferredSize(new java.awt.Dimension(50, 50));
        B_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MActionPerformed(evt);
            }
        });
        getContentPane().add(B_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        B_N.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_N.setText("N");
        B_N.setMaximumSize(new java.awt.Dimension(50, 50));
        B_N.setMinimumSize(new java.awt.Dimension(25, 25));
        B_N.setPreferredSize(new java.awt.Dimension(50, 50));
        B_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_NActionPerformed(evt);
            }
        });
        getContentPane().add(B_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        B_O.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_O.setText("O");
        B_O.setMaximumSize(new java.awt.Dimension(50, 50));
        B_O.setMinimumSize(new java.awt.Dimension(25, 25));
        B_O.setPreferredSize(new java.awt.Dimension(50, 50));
        B_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_OActionPerformed(evt);
            }
        });
        getContentPane().add(B_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        B_P.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_P.setText("P");
        B_P.setMaximumSize(new java.awt.Dimension(50, 50));
        B_P.setMinimumSize(new java.awt.Dimension(25, 25));
        B_P.setPreferredSize(new java.awt.Dimension(50, 50));
        B_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PActionPerformed(evt);
            }
        });
        getContentPane().add(B_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        B_Q.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_Q.setText("Q");
        B_Q.setMaximumSize(new java.awt.Dimension(50, 50));
        B_Q.setMinimumSize(new java.awt.Dimension(25, 25));
        B_Q.setPreferredSize(new java.awt.Dimension(50, 50));
        B_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_QActionPerformed(evt);
            }
        });
        getContentPane().add(B_Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        B_R.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_R.setText("R");
        B_R.setMaximumSize(new java.awt.Dimension(50, 50));
        B_R.setMinimumSize(new java.awt.Dimension(25, 25));
        B_R.setPreferredSize(new java.awt.Dimension(50, 50));
        B_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RActionPerformed(evt);
            }
        });
        getContentPane().add(B_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        B_S.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_S.setText("S");
        B_S.setMaximumSize(new java.awt.Dimension(50, 50));
        B_S.setMinimumSize(new java.awt.Dimension(25, 25));
        B_S.setPreferredSize(new java.awt.Dimension(50, 50));
        B_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SActionPerformed(evt);
            }
        });
        getContentPane().add(B_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        B_T.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_T.setText("T");
        B_T.setMaximumSize(new java.awt.Dimension(50, 50));
        B_T.setMinimumSize(new java.awt.Dimension(25, 25));
        B_T.setPreferredSize(new java.awt.Dimension(50, 50));
        B_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TActionPerformed(evt);
            }
        });
        getContentPane().add(B_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        B_U.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_U.setText("U");
        B_U.setMaximumSize(new java.awt.Dimension(50, 50));
        B_U.setMinimumSize(new java.awt.Dimension(25, 25));
        B_U.setPreferredSize(new java.awt.Dimension(50, 50));
        B_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_UActionPerformed(evt);
            }
        });
        getContentPane().add(B_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        B_V.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_V.setText("V");
        B_V.setMaximumSize(new java.awt.Dimension(50, 50));
        B_V.setMinimumSize(new java.awt.Dimension(25, 25));
        B_V.setPreferredSize(new java.awt.Dimension(50, 50));
        B_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VActionPerformed(evt);
            }
        });
        getContentPane().add(B_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        B_W.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_W.setText("W");
        B_W.setMaximumSize(new java.awt.Dimension(50, 50));
        B_W.setMinimumSize(new java.awt.Dimension(25, 25));
        B_W.setPreferredSize(new java.awt.Dimension(50, 50));
        B_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_WActionPerformed(evt);
            }
        });
        getContentPane().add(B_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

        B_X.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_X.setText("X");
        B_X.setMaximumSize(new java.awt.Dimension(50, 50));
        B_X.setMinimumSize(new java.awt.Dimension(25, 25));
        B_X.setPreferredSize(new java.awt.Dimension(50, 50));
        B_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_XActionPerformed(evt);
            }
        });
        getContentPane().add(B_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        B_Y.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_Y.setText("Y");
        B_Y.setMaximumSize(new java.awt.Dimension(50, 50));
        B_Y.setMinimumSize(new java.awt.Dimension(25, 25));
        B_Y.setPreferredSize(new java.awt.Dimension(50, 50));
        B_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_YActionPerformed(evt);
            }
        });
        getContentPane().add(B_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        B_Z.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B_Z.setText("Z");
        B_Z.setMaximumSize(new java.awt.Dimension(50, 50));
        B_Z.setMinimumSize(new java.awt.Dimension(25, 25));
        B_Z.setPreferredSize(new java.awt.Dimension(50, 50));
        B_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ZActionPerformed(evt);
            }
        });
        getContentPane().add(B_Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        lbl_letra1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra1.setText("J");
        lbl_letra1.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        lbl_letra2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra2.setText("A");
        lbl_letra2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 40, -1));

        lbl_letra3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra3.setText("V");
        lbl_letra3.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        lbl_letra4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_letra4.setText("A");
        lbl_letra4.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(lbl_letra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        lbl_u1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u1.setText("_");
        getContentPane().add(lbl_u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        lbl_u2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u2.setText("_");
        getContentPane().add(lbl_u2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lbl_u3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u3.setText("_");
        getContentPane().add(lbl_u3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        lbl_u4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbl_u4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_u4.setText("_");
        getContentPane().add(lbl_u4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        lbl_erros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_erros.setText("0");
        getContentPane().add(lbl_erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 30, -1));

        lbl_txt_erros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_txt_erros.setText("Erros:");
        getContentPane().add(lbl_txt_erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        lbl_erro0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_48/erro_0.jpg"))); // NOI18N
        getContentPane().add(lbl_erro0, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 220));

        lbl_erro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_48/erro_1.jpg"))); // NOI18N
        getContentPane().add(lbl_erro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, -1));

        lbl_erro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_48/erro_2.jpg"))); // NOI18N
        getContentPane().add(lbl_erro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, -1));

        lbl_erro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_48/erro_3.jpg"))); // NOI18N
        getContentPane().add(lbl_erro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, -1));

        lbl_erro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex_48/erro_4.jpg"))); // NOI18N
        getContentPane().add(lbl_erro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verifica_vitoria(){
        if (letras ==4){
        String msg = "<html>PARABÉNS! GANHOU!<br>Quer jogar novamente?";
        int valor = JOptionPane.showConfirmDialog(null, msg);
        /* yes -> valor = 0, no -> valor = 1, cancel -> valor = 2 */
            if (valor==0){
                inicia();
            }
            else
                this.dispose();
        }
    }
    public void inicia(){
        letras = 0;
        //ocultar todas as imagens
        lbl_erro0.show();
        lbl_erro1.hide();        
        lbl_erro2.hide();
        lbl_erro3.hide();
        lbl_erro4.hide();
        //ocultar as letras
        lbl_letra1.setVisible(false);
        lbl_letra2.setVisible(false);
        lbl_letra3.setVisible(false);
        lbl_letra4.setVisible(false);
        //reiniciar os erros a zero
        lbl_erros.setText("0");
        //colocar os botões das letras ativos
        B_A.setEnabled(true);
        B_B.setEnabled(true);
        B_C.setEnabled(true);
        B_D.setEnabled(true);
        B_E.setEnabled(true);
        B_F.setEnabled(true);
        B_G.setEnabled(true);
        B_H.setEnabled(true);
        B_I.setEnabled(true);
        B_J.setEnabled(true);
        B_K.setEnabled(true);
        B_L.setEnabled(true);
        B_M.setEnabled(true);
        B_N.setEnabled(true);
        B_O.setEnabled(true);
        B_P.setEnabled(true);
        B_Q.setEnabled(true);
        B_R.setEnabled(true);
        B_S.setEnabled(true);
        B_T.setEnabled(true);
        B_U.setEnabled(true);
        B_V.setEnabled(true);
        B_W.setEnabled(true);
        B_X.setEnabled(true);
        B_Y.setEnabled(true);
        B_Z.setEnabled(true);      
    }
    public void perdeu(){
        String msg = "<html>PERDEU!<br>Quer jogar novamente?";
        int valor = JOptionPane.showConfirmDialog(null, msg);
        /* yes -> valor = 0, no -> valor = 1, cancel -> valor = 2 */
        if (valor==0){
            inicia();
        }
        else
            this.dispose();
    }
    public void troca_imagem(){
        int erros = Integer.parseInt(lbl_erros.getText());
        erros ++;
        lbl_erros.setText(erros + "");
        if (erros==1){
            lbl_erro0.setVisible(false);
            lbl_erro1.setVisible(true);
        }
        else if (erros==2){
            lbl_erro1.setVisible(false);
            lbl_erro2.setVisible(true);
        }
        else if (erros==3){
            lbl_erro2.setVisible(false);
            lbl_erro3.setVisible(true);
        }
        else{
            lbl_erro3.setVisible(false);
            lbl_erro4.setVisible(true);
        }
    }
    private void B_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BActionPerformed
        // TODO add your handling code here:
        this.B_B.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_BActionPerformed

    private void B_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CActionPerformed
        // TODO add your handling code here:
        this.B_C.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_CActionPerformed

    private void B_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_DActionPerformed
        // TODO add your handling code here:
        this.B_D.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_DActionPerformed

    private void B_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EActionPerformed
        // TODO add your handling code here:
        this.B_E.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_EActionPerformed

    private void B_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FActionPerformed
        // TODO add your handling code here:
        this.B_F.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_FActionPerformed

    private void B_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GActionPerformed
        // TODO add your handling code here:
        this.B_G.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_GActionPerformed

    private void B_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HActionPerformed
        // TODO add your handling code here:
        this.B_H.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_HActionPerformed

    private void B_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IActionPerformed
        // TODO add your handling code here:
        this.B_I.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_IActionPerformed

    private void B_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_KActionPerformed
        // TODO add your handling code here:
        this.B_K.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_KActionPerformed

    private void B_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LActionPerformed
        // TODO add your handling code here:
        this.B_L.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_LActionPerformed

    private void B_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MActionPerformed
        // TODO add your handling code here:
        this.B_M.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_MActionPerformed

    private void B_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NActionPerformed
        // TODO add your handling code here:
        this.B_N.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_NActionPerformed

    private void B_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_OActionPerformed
        // TODO add your handling code here:
        this.B_O.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_OActionPerformed

    private void B_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PActionPerformed
        // TODO add your handling code here:
        this.B_P.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_PActionPerformed

    private void B_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_QActionPerformed
        // TODO add your handling code here:
        this.B_Q.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_QActionPerformed

    private void B_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RActionPerformed
        // TODO add your handling code here:
        this.B_R.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_RActionPerformed

    private void B_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SActionPerformed
        // TODO add your handling code here:
        this.B_S.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_SActionPerformed

    private void B_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TActionPerformed
        // TODO add your handling code here:
        this.B_T.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_TActionPerformed

    private void B_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_UActionPerformed
        // TODO add your handling code here:
        this.B_U.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_UActionPerformed
    
    private void B_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_WActionPerformed
        // TODO add your handling code here:
        this.B_W.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_WActionPerformed

    private void B_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_XActionPerformed
        // TODO add your handling code here:
        this.B_X.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_XActionPerformed

    private void B_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_YActionPerformed
        // TODO add your handling code here:
        this.B_Y.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_YActionPerformed

    private void B_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ZActionPerformed
        // TODO add your handling code here:
        this.B_Z.setEnabled(false);
        int erros = Integer.parseInt(lbl_erros.getText());
        if (erros==4)
            perdeu();
        else
            troca_imagem();
    }//GEN-LAST:event_B_ZActionPerformed

    private void B_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VActionPerformed
        // TODO add your handling code here:
        //Quando clico V
        letras++;
        lbl_letra3.setVisible(true);       
        this.B_V.setEnabled(false);
        verifica_vitoria();        
    }//GEN-LAST:event_B_VActionPerformed

    private void B_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra2.setVisible(true);
        letras++;
        lbl_letra4.setVisible(true);
        this.B_A.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_B_AActionPerformed

    private void B_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_JActionPerformed
        // TODO add your handling code here:
        letras++;
        lbl_letra1.setVisible(true);        
        this.B_J.setEnabled(false);
        verifica_vitoria();
    }//GEN-LAST:event_B_JActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fEnforcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fEnforcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fEnforcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fEnforcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fEnforcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B_A;
    public javax.swing.JButton B_B;
    public javax.swing.JButton B_C;
    public javax.swing.JButton B_D;
    public javax.swing.JButton B_E;
    public javax.swing.JButton B_F;
    public javax.swing.JButton B_G;
    public javax.swing.JButton B_H;
    public javax.swing.JButton B_I;
    public javax.swing.JButton B_J;
    public javax.swing.JButton B_K;
    public javax.swing.JButton B_L;
    public javax.swing.JButton B_M;
    public javax.swing.JButton B_N;
    public javax.swing.JButton B_O;
    public javax.swing.JButton B_P;
    public javax.swing.JButton B_Q;
    public javax.swing.JButton B_R;
    public javax.swing.JButton B_S;
    public javax.swing.JButton B_T;
    public javax.swing.JButton B_U;
    public javax.swing.JButton B_V;
    public javax.swing.JButton B_W;
    public javax.swing.JButton B_X;
    public javax.swing.JButton B_Y;
    public javax.swing.JButton B_Z;
    public javax.swing.JLabel lbl_erro0;
    public javax.swing.JLabel lbl_erro1;
    public javax.swing.JLabel lbl_erro2;
    public javax.swing.JLabel lbl_erro3;
    public javax.swing.JLabel lbl_erro4;
    public javax.swing.JLabel lbl_erros;
    public javax.swing.JLabel lbl_letra1;
    public javax.swing.JLabel lbl_letra2;
    public javax.swing.JLabel lbl_letra3;
    public javax.swing.JLabel lbl_letra4;
    private javax.swing.JLabel lbl_txt_erros;
    private javax.swing.JLabel lbl_u1;
    private javax.swing.JLabel lbl_u2;
    private javax.swing.JLabel lbl_u3;
    private javax.swing.JLabel lbl_u4;
    // End of variables declaration//GEN-END:variables
}
