/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_39;

/**
 *
 * @author michael
 */
public class fCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form fCalculadora
     */
    public fCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNum = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnVirgula = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        lbl_oper = new javax.swing.JLabel();
        lbl_temp = new javax.swing.JLabel();
        btnCE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("calc");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNum.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNum.setText("0");
        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 30));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn2.setText("2");
        btn2.setMaximumSize(new java.awt.Dimension(50, 50));
        btn2.setMinimumSize(new java.awt.Dimension(50, 50));
        btn2.setPreferredSize(new java.awt.Dimension(50, 50));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn1.setText("1");
        btn1.setMaximumSize(new java.awt.Dimension(50, 50));
        btn1.setMinimumSize(new java.awt.Dimension(50, 50));
        btn1.setPreferredSize(new java.awt.Dimension(50, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn3.setText("3");
        btn3.setMaximumSize(new java.awt.Dimension(50, 50));
        btn3.setMinimumSize(new java.awt.Dimension(50, 50));
        btn3.setPreferredSize(new java.awt.Dimension(50, 50));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn4.setText("4");
        btn4.setMaximumSize(new java.awt.Dimension(50, 50));
        btn4.setMinimumSize(new java.awt.Dimension(50, 50));
        btn4.setPreferredSize(new java.awt.Dimension(50, 50));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn5.setText("5");
        btn5.setMaximumSize(new java.awt.Dimension(50, 50));
        btn5.setMinimumSize(new java.awt.Dimension(50, 50));
        btn5.setPreferredSize(new java.awt.Dimension(50, 50));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn6.setText("6");
        btn6.setMaximumSize(new java.awt.Dimension(50, 50));
        btn6.setMinimumSize(new java.awt.Dimension(50, 50));
        btn6.setPreferredSize(new java.awt.Dimension(50, 50));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn7.setText("7");
        btn7.setMaximumSize(new java.awt.Dimension(50, 50));
        btn7.setMinimumSize(new java.awt.Dimension(50, 50));
        btn7.setPreferredSize(new java.awt.Dimension(50, 50));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn8.setText("8");
        btn8.setMaximumSize(new java.awt.Dimension(50, 50));
        btn8.setMinimumSize(new java.awt.Dimension(50, 50));
        btn8.setPreferredSize(new java.awt.Dimension(50, 50));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn9.setText("9");
        btn9.setMaximumSize(new java.awt.Dimension(50, 50));
        btn9.setMinimumSize(new java.awt.Dimension(50, 50));
        btn9.setPreferredSize(new java.awt.Dimension(50, 50));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        btn0.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(50, 50));
        btn0.setMinimumSize(new java.awt.Dimension(50, 50));
        btn0.setPreferredSize(new java.awt.Dimension(50, 50));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, -1));

        btnDiv.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDiv.setText("/");
        btnDiv.setMaximumSize(new java.awt.Dimension(50, 50));
        btnDiv.setMinimumSize(new java.awt.Dimension(50, 50));
        btnDiv.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        getContentPane().add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        btnVirgula.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVirgula.setText(",");
        btnVirgula.setMaximumSize(new java.awt.Dimension(50, 50));
        btnVirgula.setMinimumSize(new java.awt.Dimension(50, 50));
        btnVirgula.setPreferredSize(new java.awt.Dimension(50, 50));
        btnVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVirgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVirgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        btnMais.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMais.setText("+");
        btnMais.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMais.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMais.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });
        getContentPane().add(btnMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        btnMenos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMenos.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMenos.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setMaximumSize(new java.awt.Dimension(50, 50));
        btnIgual.setMinimumSize(new java.awt.Dimension(50, 50));
        btnIgual.setPreferredSize(new java.awt.Dimension(50, 50));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        getContentPane().add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 110));

        btnMult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMult.setText("*");
        btnMult.setMaximumSize(new java.awt.Dimension(50, 50));
        btnMult.setMinimumSize(new java.awt.Dimension(50, 50));
        btnMult.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });
        getContentPane().add(btnMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));
        getContentPane().add(lbl_oper, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, 20));
        getContentPane().add(lbl_temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 110, 20));

        btnCE.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCE.setText("CE");
        btnCE.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCE.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // TODO add your handling code here:
        lbl_temp.setText(txtNum.getText());
        lbl_oper.setText("div");
        btnVirgula.setEnabled(true);
        txtNum.setText("0");
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVirgulaActionPerformed
        // TODO add your handling code here:
        if (Float.parseFloat(txtNum.getText())==0)
            txtNum.setText("0.");
        else
            txtNum.setText(txtNum.getText()+".");
        btnVirgula.setEnabled(false);
    }//GEN-LAST:event_btnVirgulaActionPerformed

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisActionPerformed
        // TODO add your handling code here:
        lbl_temp.setText(txtNum.getText());
        lbl_oper.setText("som");
        btnVirgula.setEnabled(true);
        txtNum.setText("0");
    }//GEN-LAST:event_btnMaisActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
        lbl_temp.setText(txtNum.getText());
        lbl_oper.setText("dif");
        btnVirgula.setEnabled(true);
        txtNum.setText("0");
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        double n1, n2, resultado=0;
        n1 = Double.parseDouble(lbl_temp.getText());
        n2 = Double.parseDouble(txtNum.getText());
        if (lbl_oper.getText().equals("som"))
            resultado = n1 + n2;
        if (lbl_oper.getText().equals("dif"))
            resultado = n1 - n2;
        if (lbl_oper.getText().equals("mult"))
            resultado = n1 * n2;
        if (lbl_oper.getText().equals("div"))
            resultado = n1 / n2;
        txtNum.setText(resultado + "");
        lbl_temp.setText("");
        lbl_oper.setText("");
        btnVirgula.setEnabled(true);
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
        lbl_temp.setText(txtNum.getText());
        lbl_oper.setText("mult");
        btnVirgula.setEnabled(true);
        txtNum.setText("0");
    }//GEN-LAST:event_btnMultActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("0");        
        else 
            txtNum.setText(txtNum.getText()+"0");        
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("1");        
        else 
            txtNum.setText(txtNum.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("2");        
        else 
            txtNum.setText(txtNum.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("3");        
        else 
            txtNum.setText(txtNum.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("4");        
        else 
            txtNum.setText(txtNum.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("5");        
        else 
            txtNum.setText(txtNum.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("6");        
        else 
            txtNum.setText(txtNum.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("7");        
        else 
            txtNum.setText(txtNum.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("8");        
        else 
            txtNum.setText(txtNum.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (txtNum.getText().equals("0"))
            txtNum.setText("9");        
        else 
            txtNum.setText(txtNum.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
        btnVirgula.setEnabled(true);
        lbl_temp.setText("");
        lbl_oper.setText("");
        txtNum.setText("0");
    }//GEN-LAST:event_btnCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnVirgula;
    public javax.swing.JLabel lbl_oper;
    public javax.swing.JLabel lbl_temp;
    public javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
