/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ficha_validacao2;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class fValid2 extends javax.swing.JFrame {

    /**
     * Creates new form fValid2
     */
    public fValid2() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_palavra = new javax.swing.JLabel();
        lbl_texto = new javax.swing.JLabel();
        lbl_pontos = new javax.swing.JLabel();
        lbl_pic1 = new javax.swing.JLabel();
        lbl_pic2 = new javax.swing.JLabel();
        lbl_pic3 = new javax.swing.JLabel();
        lbl_pic4 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn_novojogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_palavra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_palavra.setText("Ginástica");
        getContentPane().add(lbl_palavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 40));

        lbl_texto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_texto.setText("Pontos:");
        getContentPane().add(lbl_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 35, -1, 30));

        lbl_pontos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_pontos.setText("0");
        getContentPane().add(lbl_pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 50, 40));

        lbl_pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha_validacao2/pic1.jpg"))); // NOI18N
        getContentPane().add(lbl_pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 170, 170));

        lbl_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha_validacao2/pic2.jpg"))); // NOI18N
        getContentPane().add(lbl_pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 170, 170));

        lbl_pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha_validacao2/pic3.jpg"))); // NOI18N
        getContentPane().add(lbl_pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, 170));

        lbl_pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha_validacao2/pic4.jpg"))); // NOI18N
        getContentPane().add(lbl_pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 170, 170));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn1.setText("?");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn2.setText("?");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 170, -1));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn3.setText("?");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 170, -1));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn4.setText("?");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 170, -1));

        btn_novojogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_novojogo.setText("InsertCoin");
        btn_novojogo.setToolTipText("");
        btn_novojogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novojogoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_novojogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void acertou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\temp\\sucesso.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void errou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\temp\\erro.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    public void ganhou(){
        try{
            File wav = new File("C:\\Users\\micha\\Documents\\NetBeansProjects\\temp\\ganhou.wav");
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(wav));
            // reproduzir o áudio
            clip.start();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText()=="?"){
            if (lbl_palavra.getText()=="Basquetebol"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Acertou!");
                lbl_palavra.setText("Boxe");
                btn1.setText("Basquetebol");
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Errou! Volte a tentar");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Já acertou esse desporto!");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText()=="?"){
            if (lbl_palavra.getText()=="Voleibol"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Acertou!");
                lbl_palavra.setText("Basquetebol");
                btn2.setText("Voleibol");
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Errou! Volte a tentar");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Já acertou esse desporto!");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText()=="?"){
            if (lbl_palavra.getText()=="Boxe"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                ganhou();
                JOptionPane.showMessageDialog(null, "Acertou todos os desportos!");
                lbl_palavra.setText("Parabéns!");
                btn3.setText("Boxe");
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Errou! Volte a tentar");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Já acertou esse desporto!");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn4.getText()=="?"){
            if (lbl_palavra.getText()=="Ginástica"){
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts + 10;
                lbl_pontos.setText(pts+"");
                acertou();
                JOptionPane.showMessageDialog(null, "Acertou!");
                lbl_palavra.setText("Voleibol");
                btn4.setText("Ginástica");
            }
            else{
                double pts = Double.parseDouble(lbl_pontos.getText());
                pts = pts - 5;
                lbl_pontos.setText(pts+"");
                errou();
                JOptionPane.showMessageDialog(null, "Errou! Volte a tentar");
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Já acertou esse desporto!");        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn_novojogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novojogoActionPerformed
        // TODO add your handling code here:
        lbl_palavra.setText("Ginástica");
        lbl_pontos.setText("0");
        btn1.setText("?");
        btn2.setText("?");
        btn3.setText("?");
        btn4.setText("?");
    }//GEN-LAST:event_btn_novojogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fValid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fValid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fValid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fValid2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fValid2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn_novojogo;
    public javax.swing.JLabel lbl_palavra;
    private javax.swing.JLabel lbl_pic1;
    private javax.swing.JLabel lbl_pic2;
    private javax.swing.JLabel lbl_pic3;
    private javax.swing.JLabel lbl_pic4;
    public javax.swing.JLabel lbl_pontos;
    private javax.swing.JLabel lbl_texto;
    // End of variables declaration//GEN-END:variables
}
