/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_47;

/**
 *
 * @author michael
 */
public class fTabuada extends javax.swing.JFrame {

    /**
     * Creates new form fTabuada
     */
    public fTabuada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_num = new javax.swing.JLabel();
        cb_num = new javax.swing.JComboBox<>();
        btn_calc = new javax.swing.JButton();
        btn_limp = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_num.setText("Qual o número para ver a tabuada?");
        getContentPane().add(lbl_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, -1));

        cb_num.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cb_num.setToolTipText("");
        cb_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_numActionPerformed(evt);
            }
        });
        getContentPane().add(cb_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        btn_calc.setText("Calcular");
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        btn_limp.setText("Limpar");
        btn_limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 210, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed
        // TODO add your handling code here:
        int i, num, resultado;
        num = cb_num.getSelectedIndex()+1;
        String resposta = "<html>";
        
        for (i=1; i<=10; i++){
            resultado = num * i;
            resposta = resposta + i + "*" + num + "=" + resultado + "<br>";
        }
        
        resposta = resposta + "</html>";
        lbl_resultado.setText(resposta);
    }//GEN-LAST:event_btn_calcActionPerformed

    private void btn_limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpActionPerformed
        // TODO add your handling code here:
        cb_num.setSelectedIndex(0);
        lbl_resultado.setText("Escolha um número");
    }//GEN-LAST:event_btn_limpActionPerformed

    private void cb_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_numActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTabuada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTabuada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calc;
    private javax.swing.JButton btn_limp;
    public javax.swing.JComboBox<String> cb_num;
    private javax.swing.JLabel lbl_num;
    public javax.swing.JLabel lbl_resultado;
    // End of variables declaration//GEN-END:variables
}
