/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_41;

/**
 *
 * @author michael
 */
public class fArPer extends javax.swing.JFrame {

    /**
     * Creates new form fArPer
     */
    public fArPer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_comp = new javax.swing.JLabel();
        lbl_larg = new javax.swing.JLabel();
        txt_comp = new javax.swing.JTextField();
        txt_larg = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        btnApag = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_comp.setText("Comprimento:");
        getContentPane().add(lbl_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lbl_larg.setText("Largura:");
        getContentPane().add(lbl_larg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        getContentPane().add(txt_comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 150, -1));

        txt_larg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_largActionPerformed(evt);
            }
        });
        getContentPane().add(txt_larg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, -1));

        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        btnApag.setText("Apagar");
        btnApag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagActionPerformed(evt);
            }
        });
        getContentPane().add(btnApag, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 320, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_largActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_largActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_largActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        double lado1, lado2;
        lado1 = Double.parseDouble(txt_comp.getText());
        lado2 = Double.parseDouble(txt_larg.getText());
        double area = lado1 * lado2;
        double perimetro = (lado1 * 2) + (lado2 * 2);
        String resultado = "<html>A área é " + area + "<br>O perímetro é " 
                + perimetro;
        lbl_resultado.setText(resultado);
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnApagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagActionPerformed
        // TODO add your handling code here:
        txt_comp.setText("");
        txt_larg.setText("");
        lbl_resultado.setText("");
    }//GEN-LAST:event_btnApagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fArPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fArPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fArPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fArPer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fArPer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApag;
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel lbl_comp;
    private javax.swing.JLabel lbl_larg;
    public javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_comp;
    private javax.swing.JTextField txt_larg;
    // End of variables declaration//GEN-END:variables
}
