/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex_43;

/**
 *
 * @author michael
 */
public class fConverter extends javax.swing.JFrame {

    /**
     * Creates new form fConverter
     */
    public fConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_polegadas = new javax.swing.JLabel();
        txt_inch = new javax.swing.JTextField();
        btnConv = new javax.swing.JButton();
        btnApag = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_polegadas.setText("Valor em polegadas:");
        getContentPane().add(lbl_polegadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, -1));
        getContentPane().add(txt_inch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 110, -1));

        btnConv.setText("Converter");
        btnConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvActionPerformed(evt);
            }
        });
        getContentPane().add(btnConv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        btnApag.setText("Apagar");
        btnApag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagActionPerformed(evt);
            }
        });
        getContentPane().add(btnApag, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 30));

        lbl_resultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 170, 240, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvActionPerformed
        // TODO add your handling code here:
        double inch;
        inch = Double.parseDouble(txt_inch.getText());
        double cm = inch * 2.54;
        String resultado = "O valor em cm é " + cm;
        lbl_resultado.setText(resultado);
    }//GEN-LAST:event_btnConvActionPerformed

    private void btnApagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagActionPerformed
        // TODO add your handling code here:
        txt_inch.setText("");
        lbl_resultado.setText("");
    }//GEN-LAST:event_btnApagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApag;
    private javax.swing.JButton btnConv;
    private javax.swing.JLabel lbl_polegadas;
    public javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_inch;
    // End of variables declaration//GEN-END:variables
}
